name: Build, Push, Deploy.

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  build_and_push:
    if: github.event.pull_request.merged == true

    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Extract metadata (labels, tags, etc.) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tuyishimire/simple-cicd-project-app
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tuyishimire/simple-cicd-project-app:latest
          labels: ${{ steps.meta.outputs.labels }}